#!/usr/bin/env ansible-playbook

- name: Create a sample zone file
  hosts: localhost
  tasks:

    - name: Create the zone file for zone {{ zone.name }}
      template:
          src: zone.db.j2
          dest: "{{ zone.name }}.db"
      vars:
          zone: "{{ query('netbox.netbox.nb_lookup', 'zones', plugin='netbox_dns',
                           api_endpoint='https://192.168.106.105/',
                           api_filter='name=example.com',
                           token='b02c088f58ccf5d24d7d46509809f4ef6958143c')
                    | map(attribute='value')
                    | first }}"
          records: "{{ query('netbox.netbox.nb_lookup', 'records', plugin='netbox_dns',
                             api_endpoint='https://192.168.106.105/',
                             api_filter='zone='+zone.name,
                             token='b02c088f58ccf5d24d7d46509809f4ef6958143c')
                       | map(attribute='value') }}"
